// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BZVKzHqC-IH3MDhaWoI6Ge2IGXewThE',
    appId: '1:762981530901:web:3ccaa21bfa09d443987d1c',
    messagingSenderId: '762981530901',
    projectId: 'agora-multiple-channels',
    authDomain: 'agora-multiple-channels.firebaseapp.com',
    storageBucket: 'agora-multiple-channels.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRu-ZTL2bf4KN0OS8D6T1hfXmumWQKkF0',
    appId: '1:762981530901:android:edee4e59db323301987d1c',
    messagingSenderId: '762981530901',
    projectId: 'agora-multiple-channels',
    storageBucket: 'agora-multiple-channels.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFTgvkRVf48j2Ar8IpA5iWoP7BRtE77E',
    appId: '1:762981530901:ios:58766c6e6d585fad987d1c',
    messagingSenderId: '762981530901',
    projectId: 'agora-multiple-channels',
    storageBucket: 'agora-multiple-channels.appspot.com',
    iosClientId:
        '762981530901-sksp4liaa9heuln9imu596j30mb70e79.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraUiKit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFTgvkRVf48j2Ar8IpA5iWoP7BRtE77E',
    appId: '1:762981530901:ios:58766c6e6d585fad987d1c',
    messagingSenderId: '762981530901',
    projectId: 'agora-multiple-channels',
    storageBucket: 'agora-multiple-channels.appspot.com',
    iosClientId:
        '762981530901-sksp4liaa9heuln9imu596j30mb70e79.apps.googleusercontent.com',
    iosBundleId: 'com.example.agoraUiKit',
  );
}
